### ISSUE TITLE
(High) [Usability] Pick appropriate default landing screen

### ISSUE THREAD

**Issue by MatthewLangille** [MattsTeam/toBeNamed#52]
Finalize this choice
Change the app so that the selected screen is the first displayed
Work out any usability friction if if you feel anything

**Comment by ChrisLewis0** [comment]
Finished

**Comment by vanessahlyan** [comment]
set Favorites as new Home screen, "Home" is now "Search" fragment
updated Bottom Navigation and Action Bars based on new organization
Now, the fragments on bottom navigation bar are: Home (aka Favorites), Search, Messages, Calendar, Profile
