### ISSUE TITLE
(Low) [Usability] Handle case when nothing is selected (mentor or category) on category screen

### ISSUE THREAD

**Issue by MatthewLangille** [MattsTeam/toBeNamed#53]
Consider UI change so that something is always selected
Consider changing wording based on whether you're a mentor or mentee

This may be too low-pri to bother with considering the deadline. If so, just have a story in mind for it

**Comment by vanessahlyan** [comment]
Creates toast if neither mentor nor mentee is selected
Allows user to sign up even if no category is selected
Home Page appears different for mentors vs mentees
